---
title: "Exercise sheet 3: T-Coffee"
---

# Exercise 1

You are given the sequences $a$, $b$ and $c$

$$
a = CACCGG\\
b = ACCAAG\\
c = AACACC\\
$$

The pairwise optimal alignments of Pool $P$ were calculated as:

~~~
a: CACCG_G          a: __CACCGG     b: ACCAAG
    |||: |               ||||          |:||::
b: _ACCAAG          c: AACACC__     c: AACACC
~~~

#### {.tabset}

##### Question 1A

::: {.question data-latex=""}

Calculate the primary library ($L$)
:::


##### Formulae

::: {.answer data-latex=""}

init: $L^{x,y}_{i,j}=0$

$\forall$ alignments $A$ of sequence $s^x$ $^y$ in pool $P$

$weight(A) = \dfrac{number\ of\ matches}{min(len(s^x), len(s^y))}$

$\forall$ aligned positions $i,j$

$L^{x,y}_{i,j}=L^{x,y}_{i,j} + weight(A)$

:::


##### Solution

::: {.answer data-latex=""}

$L^{a,b}_{2,1}=L^{a,b}_{3,2}=L^{a,b}_{4,3}=L^{a,b}_{6,6}=100*\frac{4}{6}=67$ and all other $L^{a,b}_{i,j}=0$

$L^{a,c}_{1,3}=L^{a,c}_{2,4}=L^{a,c}_{3,5}=L^{a,c}_{4,6}=100*\frac{4}{6}=67$ and all other $L^{a,c}_{i,j}=0$

$L^{b,c}_{1,1}=L^{b,c}_{3,3}=L^{b,c}_{4,4}=100*\frac{3}{6}=50$ and all other $L^{b,c}_{i,j}=0$
:::
#### {-}

#### {.tabset}

##### Question 1B

::: {.question data-latex=""}

Calculate the extended library ($EL$)
:::

##### Solution

::: {.answer data-latex=""}

The original Library doesn't change as there are no edges enforcing certain connections. Hence

$EL^{s1,s2}_{i,j}=L^{s1,s2}_{i,j} \qquad \forall L^{s1,s2}_{i,j}\neq 0$

and the following weights are added:

~~~
a: CACCG_G     
    |||: |    
b: _ACCAAG   
    |:||::
c:  AACACC
    * *
~~~

$EL^{a,b}_{1,3}=EL^{a,b}_{2,4}=50$

~~~
a: __CACCGG     
     ||||       
c: AACACC__     
   |:||::
b: ACCAAG
     **
~~~

$EL^{a,c}_{2,1}=EL^{a,c}_{4,3}=50$


~~~
b:    ACCAAG
      |||: |    
a:   CACCG_G     
     |||| 
c: AACACC
      ***
~~~

$EL^{b,c}_{1,4}=EL^{b,c}_{2,5}=EL^{b,c}_{3,6}=67$

:::
#### {-}

#### {.tabset}

##### Question 1C


Realign the sequences $b$ and $c$ using EL for scoring and gap costs and mismatch costs of 0

##### Solution

::: {.answer data-latex=""}

| - | - | A  | C   | C   | A   | A   | G   |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| __-__ | 0 | 0  | 0   | 0   | 0   | 0   | 0   |
| __A__ | 0 | 50 | 50  | 50  | 50  | 50  | 50  |
| __A__ | 0 | 50 | 50  | 50  | 50  | 50  | 50  |
| __C__ | 0 | 50 | 50  | 100 | 100 | 100 | 100 |
| __A__ | 0 | 67 | 67  | 100 | 150 | 150 | 150 |
| __C__ | 0 | 67 | 133 | 133 | 150 | 150 | 150 |
| __C__ | 0 | 67 | 133 | 200 | 200 | 200 | 200 |

:::
#### {-}


#### {.tabset}

##### Question 1C

Do the other alignments a-b and a-c change? Provide arguments, without calculating new ali-
gnments.

##### Solution

No. The newly added alignment scores in $E$L represent edges that are incompatible with the
current best alignments and can not score higher.

#### {-}

#### {.tabset}


##### Question 1E

Sketch the Guide Tree

##### Solution

$((a,c),b)$  or $((a,b),c)$

#### {-}

#### {.tabset}

##### Question 1F

Perform a progressive alignment by aligning sequence b to the already existing alignment $A(a, c)$.
To score a match between $b$ and $A(a, c)$ use the sum $EL^{a,b}$ + $EL^{b,c}$ with the correct indices.
Show the resulting multiple sequence alignment.

##### Solution

| -<br />- | -<br />- | -<br />A  | -<br />A  | C<br />C   | A<br />A   | C<br />C   | C<br />C   | G<br />-   | G<br />-   |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| __-__ | 0 | 0  | 0  | 0   | 0   | 0   | 0   | 0   | 0   |
| __A__ | 0 | 50 | 50 | 50  | 133 | 133 | 133 | 133 | 133 |
| __C__ | 0 | 50 | 50 | 50  | 133 | 267 | 267 | 267 | 267 |
| __C__ | 0 | 50 | 50 | 150 | 150 | 267 | 400 | 400 | 400 |
| __A__ | 0 | 50 | 50 | 150 | 250 | 267 | 400 | 400 | 400 |
| __A__ | 0 | 50 | 50 | 150 | 250 | 267 | 400 | 400 | 400 |
| __G__ | 0 | 50 | 50 | 150 | 250 | 267 | 400 | 400 | 467 |

#### {-}

-------------------------------------------

```{r, include=knitr::is_html_output(), echo=F}
knitr::asis_output('Download: <a href="exercise-sheet-3.pdf" title="Download PDF Version">PDF Version</a> of this page.')
```
